/**
 * Material Symbols codepoints for every icon this app renders.
 *
 * The font supports two ways of picking a glyph: the ligature ("favorite") or
 * the character itself. Ligatures put the icon's *name* into the DOM as real
 * text, which has two consequences:
 *
 *   - accessibility checkers read it as the control's visible label, so an
 *     icon button reads as "add_shopping_cart" and trips WCAG 2.5.3;
 *   - if the icon font fails or is slow to load, the raw word shows on screen.
 *
 * Rendering the codepoint avoids both. Values are the official ones from
 * google/material-design-icons (MaterialSymbolsOutlined codepoints); a name
 * that is missing here falls back to its ligature in Icon.jsx.
 */
const ICON_CODEPOINTS = {
  account_balance_wallet: "e850",
  account_circle: "f20b",
  add: "e145",
  add_a_photo: "e439",
  add_shopping_cart: "e854",
  apartment: "ea40",
  arrow_back: "e5c4",
  arrow_forward: "e5c8",
  assignment: "e85d",
  assistant: "e39f",
  badge: "ea67",
  bed: "efdf",
  biotech: "ea3a",
  block: "f08c",
  bookmark_border: "e8e7",
  calendar_month: "ebcc",
  calendar_today: "e935",
  calendar_view_day: "e936",
  call: "f0d4",
  cancel: "e888",
  category: "e72c",
  celebration: "ea65",
  check: "e668",
  check_circle: "f0be",
  chevron_left: "e5cb",
  chevron_right: "e5cc",
  close: "e5cd",
  cloud_off: "e2c1",
  cloud_upload: "e2c3",
  content_copy: "e14d",
  credit_card: "e8a1",
  cruelty_free: "e799",
  dashboard: "e871",
  dark_mode: "e51c",
  delete: "e92e",
  delete_forever: "e92b",
  description: "e873",
  details: "e3c8",
  domain: "e7ee",
  done: "e876",
  done_all: "e877",
  download: "f090",
  edit: "f097",
  edit_calendar: "e742",
  email: "e159",
  emergency: "e1eb",
  error: "f8b6",
  event: "e878",
  event_available: "e614",
  event_busy: "e615",
  event_note: "e616",
  event_repeat: "eb7b",
  event_upcoming: "f238",
  expand_more: "e5cf",
  eyebrow: "eeb3",
  favorite: "e87e",
  filter: "e3d3",
  filter_list: "e152",
  fingerprint: "e90d",
  flutter_dash: "e00b",
  format_quote: "e244",
  light_mode: "e518",
  function: "f866",
  gavel: "e90e",
  group: "ea21",
  groups: "f233",
  healing: "e3f3",
  health_and_safety: "e1d5",
  help: "e8fd",
  history: "e8b3",
  home: "e9b2",
  home_pin: "f14d",
  home_work: "f030",
  hourglass_empty: "e88b",
  house: "ea44",
  image: "e3f4",
  inbox: "e156",
  info: "e88e",
  inventory: "e179",
  inventory_2: "e1a1",
  label: "e893",
  language: "ea07",
  list: "e896",
  local_hospital: "e548",
  local_shipping: "e558",
  location_on: "f1db",
  lock: "e899",
  lock_open: "e898",
  login: "ea77",
  logout: "e9ba",
  mail: "e159",
  mark_email_read: "f18c",
  medical_information: "ebed",
  medical_services: "f109",
  menu: "e5d2",
  message: "e0c9",
  monitor_heart: "eaa2",
  my_location: "e55c",
  navigation: "e55d",
  note: "e674",
  open_in_new: "e89e",
  overview: "e4a7",
  password: "f042",
  payment: "e8a1",
  payments: "ef63",
  pending: "ef64",
  pending_actions: "f1bb",
  person: "f0d3",
  person_add: "ea4d",
  pets: "e91d",
  photo_camera: "e412",
  pill: "e11f",
  progress_activity: "e9d0",
  psychology: "ea4a",
  radio: "e03e",
  rate_review: "e560",
  receipt_long: "ef6e",
  refresh: "e5d5",
  remove: "e15b",
  replay: "e042",
  restaurant: "e56c",
  reviews: "f07c",
  route: "eacd",
  save: "e161",
  schedule: "efd6",
  search: "ef7a",
  search_off: "ea76",
  security: "e32a",
  shield_person: "f650",
  shop: "e8c9",
  shopping_bag: "f1cc",
  shopping_cart: "e8cc",
  shopping_cart_checkout: "eb88",
  shopping_cart_off: "f4f7",
  smart_toy: "f06c",
  sort: "e164",
  sound_detection_dog_barking: "f149",
  star: "f09a",
  star_border: "f09a",
  star_half: "e839",
  star_rate: "f0ec",
  step: "f6fe",
  stethoscope: "f805",
  store: "e8d1",
  storefront: "ea12",
  tab: "e8d8",
  task_alt: "e2e6",
  timeline: "e922",
  title: "e264",
  today: "e8df",
  token: "ea25",
  trending_up: "e8e5",
  upload: "f09b",
  vaccines: "e138",
  verified: "ef76",
  verified_user: "f013",
  visibility: "e8f4",
  volunteer_activism: "ea70",
  warning: "f083",
  workspace_premium: "e7af",
};

export default ICON_CODEPOINTS;
